export const defaultConfig = {
    workoutsTotal: 0,
    minutesTotal: 0,
    currentChallengeId: null,
    challenges: [
        {
            id: 1001,
            title: "The squats challenge",
            img: require("../assets/images/home/challenge_1.jpg"),
            progress: Array.from({ length: 30 }, (_, i) => false),
            durationLabel: "30 days",
            calories: 5,
            exercises: [
                {
                    title: "Squat",
                    img: require("../assets/squats.jpg"),
                    duration: 40,
                    multiple: 1,
                },
            ],
        },
        {
            id: 1002,
            title: "The push-ups challenge",
            img: require("../assets/images/home/challenge_2.jpg"),
            progress: Array.from({ length: 30 }, (_, i) => false),
            durationLabel: "30 days",
            calories: 5,
            exercises: [
                {
                    title: "Push-ups",
                    img: require("../assets/push-ups.jpg"),
                    duration: 60,
                    multiple: 1,
                },
            ],
        },
        {
            id: 1003,
            title: "The crunch challenge",
            img: require("../assets/images/home/challenge_3.jpg"),
            progress: Array.from({ length: 30 }, (_, i) => false),
            durationLabel: "30 days",
            calories: 5,
            exercises: [
                {
                    title: "Crunches",
                    img: require("../assets/crunches.png"),
                    duration: 60,
                    multiple: 1,
                },
            ],
        },
        {
            id: 1004,
            title: "The pull-ups challenge",
            img: require("../assets/images/home/challenge_4.jpg"),
            progress: Array.from({ length: 30 }, (_, i) => false),
            durationLabel: "30 days",
            calories: 5,
            exercises: [
                {
                    title: "Pull-ups",
                    img: require("../assets/pull-ups.jpg"),
                    duration: 60,
                    multiple: 1,
                },
            ],
        },
    ],
    workouts: [
        {
            id: 2001,
            title: "Burpees, Squats & Planks",
            img: require("../assets/planks.jpg"),
            progress: [],
            durationLabel: "",
            calories: 15,
            exercises: [
                {
                    title: "Plank Shoulder Taps",
                    img: require("../assets/Plank-Shoulder-Taps.jpg"),
                    duration: 4,
                    multiple: 1,
                },
                {
                    title: "Side Plank and Leg lift",
                    img: require("../assets/Side-Plank-Leg-Lift.jpg"),
                    duration: 4,
                    multiple: 2,
                },
                {
                    title: "Narrow Bodyweight Squat",
                    img: require("../assets/Narrow-Squat.jpg"),
                    duration: 4,
                    multiple: 1,
                },
                {
                    title: "Bodyweight Overhead Squats",
                    img: require("../assets/Overhead-Squat.jpg"),
                    duration: 4,
                    multiple: 1,
                },
                {
                    title: "Burpees",
                    img: require("../assets/burpees.jpg"),
                    duration: 4,
                    multiple: 1,
                },
                {
                    title: "Plank Knee Drive",
                    img: require("../assets/plank-knee-drive.jpg"),
                    duration: 4,
                    multiple: 1,
                },
            ],
        },
        {
            id: 2002,
            title: "Shape your body",
            img: require("../assets/shape-body.jpg"),
            progress: [],
            durationLabel: "",
            calories: 5,
            exercises: [
                {
                    title: "Donkey Kick",
                    img: require("../assets/donkey-kick.jpg"),
                    duration: 40,
                    multiple: 2,
                },
                {
                    title: "Squat Jacks",
                    img: require("../assets/squat-jacks.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Standing Kickback",
                    img: require("../assets/standing-kickback.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Side-lying Leg Lifts",
                    img: require("../assets/side-lying-leg-lifts.jpg"),
                    duration: 40,
                    multiple: 2,
                },
                {
                    title: "Frog Squat",
                    img: require("../assets/frog-squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Froggy Glute Lifts",
                    img: require("../assets/froggy-glute-lifts.jpg"),
                    duration: 40,
                    multiple: 1,
                },
            ],
        },
        {
            id: 2003,
            title: "HIIT Workout",
            img: require("../assets/HIIT.jpg"),
            progress: [],
            durationLabel: "",
            calories: 5,
            exercises: [
                {
                    title: "Narrow Bodyweight Squat",
                    img: require("../assets/Overhead-Squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Curtsy Squat",
                    img: require("../assets/mountain-climbers.png"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Jump Squats",
                    img: require("../assets/jump-squats.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Alternating Jump Lunges",
                    img: require("../assets/alternating-jump-lunge.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Squat with Punches",
                    img: require("../assets/squat-with-punches.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Curtsy Squat",
                    img: require("../assets/curtsy-squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
            ],
        },
        {
            id: 2004,
            title: "Squat Variations",
            img: require("../assets/squat-variations.jpg"),
            progress: [],
            durationLabel: "",
            calories: 5,
            exercises: [
                {
                    title: "Bodyweight Overhead Squats",
                    img: require("../assets/Narrow-Squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Curtsy Squat",
                    img: require("../assets/curtsy-squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Squat Side kicks",
                    img: require("../assets/squat-side-kicks.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Frog Squat",
                    img: require("../assets/frog-squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "Squat Pulse",
                    img: require("../assets/squat-pulse.jpg"),
                    duration: 40,
                    multiple: 1,
                },
                {
                    title: "In-out Jump Squat",
                    img: require("../assets/in-out-jump-squat.jpg"),
                    duration: 40,
                    multiple: 1,
                },
            ],
        },
    ],
};
